Update tlg0548.tlg001__cts__.xml
PerseusDL/canonical-greekLit pull request #1256
Opened 2021-03-23 13:34 UTC by AlisonBabeu

Standardized the title description and edition metadata to OGL standards since file is converted and showing up in Scaife.

2021-03-23 14:04 UTC, capitains-hook commented
*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-greekLit/5325)*

2021-03-23 18:02 UTC, lcerrato requested changes

2021-03-23 18:02 UTC, lcerrato commented on data/tlg0548/tlg001/__cts__.xml
> +        <ti:label xml:lang="eng">Library</ti:label>
Βιβλιοθήκη

2021-03-23 18:53 UTC, AlisonBabeu commented on data/tlg0548/tlg001/__cts__.xml
> +          Translation. Frazer, James George, Sir, 1854-1941, editor, translator. Cambridge, MA,
Will do. Thanks for reviewing.

2021-03-23 19:31 UTC, capitains-hook commented
*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-greekLit/5327)*

2021-03-24 16:42 UTC, capitains-hook commented
*[Hook UI build recap](https://ci.perseids.org/repo/PerseusDL/canonical-greekLit/5331)*

2021-03-24 16:49 UTC, lcerrato approved these changes

2021-03-24 16:49 UTC, merged