(tlg0540)_003_004
PerseusDL/canonical-greekLit pull request #1411
Opened 2023-04-14 16:09 UTC by AlisonBabeu

Next batch of Lysias files!

2023-04-14 16:36 UTC, lcerrato commented
@AlisonBabeu 
I'm wondering are these just meant to bibliographic changes or are they meant to address other header issues, too?

2023-04-14 17:40 UTC, AlisonBabeu commented
hi @lcerrato I'm addressing general header issues like adding in an editor/translator, updating the work title if necessary, as well as updating the structured bibliographic section and adding in page level links. 

I'm not touching any of the sponsor info or attributions issues at the moment.

2023-04-14 17:56 UTC, lcerrato commented
@AlisonBabeu Thanks!

2023-04-14 18:09 UTC, lcerrato requested changes

2023-04-14 18:09 UTC, lcerrato commented on data/tlg0540/tlg004/tlg0540.tlg004.perseus-grc2.xml
> +            <editor role="translator">W.R.M. Lamb</editor>
not translator here

2023-04-24 23:55 UTC, lcerrato approved these changes

2023-04-25 01:33 UTC, AlisonBabeu commented
hey @lcerrato thanks for fixing things, I have no idea how I eliminated the closing work tag in the cts_.xml files. I really miss the STOA XML validation working.

2023-04-25 01:33 UTC, merged