(greek_conversion) EpiDoc and CTS conversion work
PerseusDL/canonical-greekLit pull request #1528
Opened 2023-11-21 22:09 UTC by lcerrato

tlg0545 batch #1399

2023-11-27 15:26 UTC, AlisonBabeu commented on data/tlg0545/tlg002/tlg0545.tlg002.perseus-grc2.xml
hi @lcerrato only thing I would change on this file is in the structured bibliography. 
`<title>Claudii Aeliani de natura animalium libri xvii, varia historia, epistolae, fragmenta, Vol 2</title>`
I would delete Vol 2 here and add it in using the biblScope element! 

The same is true for tlg0545.tlg002.perseus-grc3 below! :)

2023-11-28 17:39 UTC, lcerrato commented on data/tlg0545/tlg002/tlg0545.tlg002.perseus-grc2.xml
There is a biblScope element, no?

2023-11-28 17:39 UTC, lcerrato commented on data/tlg0545/tlg003/tlg0545.tlg003.perseus-grc2.xml
This file doesn't appear to be completely done/

2023-11-28 18:57 UTC, lcerrato commented
@AlisonBabeu I appreciate your looking at these: the headers were/are very confusing!

2023-12-06 20:47 UTC, lcerrato commented
@AlisonBabeu Would you mind looking over the metadata here? I don't want to push more files/changes to this batch.

2023-12-07 16:23 UTC, AlisonBabeu commented on data/tlg0545/tlg003/__cts__.xml
This is missing the volume number.

2023-12-07 17:04 UTC, AlisonBabeu commented on data/tlg0555/tlg004/tlg0555.tlg004.perseus-grc1.xml
So @lcerrato should this be tlg0555.tlg004.perseus-grc2? And also there is no cts_.xml file for the 004 directory.

2023-12-07 17:31 UTC, lcerrato commented on data/tlg0545/tlg003/__cts__.xml
Your earlier comment said to delete the volumes in the CTS files and keep them in the biblScope? So I deleted them in the CTS files.

2023-12-07 17:32 UTC, lcerrato commented on data/tlg0555/tlg004/tlg0555.tlg004.perseus-grc1.xml
I removed an extra period in the file name.

2023-12-07 17:36 UTC, lcerrato commented on data/tlg0545/tlg003/__cts__.xml
@AlisonBabeu I think I see the issue: I thought you wanted it removed here but you were talking about the file header errors. I had it in this batch and will re-add now.

2023-12-07 17:38 UTC, AlisonBabeu requested changes
I made a comment on one file that needs a minor metadata change and there also appears to be a missing cts_.xml file for tlg0555.tlg004.

2023-12-07 17:40 UTC, lcerrato commented
@AlisonBabeu Thank you. tlg0555.tlg004 is not being converted as part of this PR.

2023-12-07 18:24 UTC, AlisonBabeu commented on data/tlg0545/tlg003/__cts__.xml
@lcerrato Sorry if I was unclear,I usually include it in both places.

2023-12-08 17:54 UTC, merged