(grc_conversion) EpiDoc and CTS conversion
PerseusDL/canonical-greekLit pull request #1573
Opened 2024-01-24 22:40 UTC by lcerrato

tlg0719 batch #1399

2024-01-25 00:44 UTC, lcerrato commented
@AlisonBabeu These titles were a little confusing so I hope that I have the Greek correct.

2024-01-25 16:05 UTC, AlisonBabeu submitted a review, later dismissed
hi @lcerrato just one minor change!

2024-01-25 17:52 UTC, lcerrato commented on data/tlg0719/tlg002/tlg0719.tlg002.perseus-grc2.xml
@AlisonBabeu Thanks. This was done a few years back so there were differences lurking in there.

2024-02-01 01:12 UTC, lcerrato commented
@AlisonBabeu 
I thought I had merged this but the first set of tlg2003 files are here now.

2024-02-05 15:12 UTC, AlisonBabeu commented on data/tlg2003/tlg001/tlg2003.tlg001.perseus-grc2.xml
I would standardize the double imprint statement in this file:
`    <imprint>
                     <publisher>William Heinemann</publisher>
                     <pubPlace>London</pubPlace>
                     <date>1913-1923</date>
                  </imprint>
                  <imprint>
                     <publisher>Harvard University Press</publisher>
                     <pubPlace>Cambridge, MA.</pubPlace>
                     <date>1913-1923</date>
                  </imprint>`

And instead use

`    <imprint>
                     <publisher>William Heinemann</publisher>
                     <pubPlace>London</pubPlace>
                     <publisher>The Macmillan Company</publisher>
                     <pubPlace>New York</pubPlace>
                     <date>1913</date>
                  </imprint>
             `
I would also consider adding a series element with the Loeb Classical Library,I've been trying to do that.

2024-02-05 16:43 UTC, lcerrato commented on data/tlg2003/tlg002/tlg2003.tlg002.perseus-grc2.xml
It is all cut/paste so it will be identical everywhere. I do not always have a template with the series info, so that is easily missed when I do these. (if the last file I was editing was not in a series, I won't have it in the header for reference, unfortunately.)

2024-02-05 16:55 UTC, AlisonBabeu requested changes
hi @lcerrato these files look good other than changing the structured bibl on all of them.

2024-02-05 18:56 UTC, AlisonBabeu reviewed
hi @lcerrato one question, why the Harvard University still? the CTS files have Heineman and Macmillan, none of the imprints in the volumes in Internet Archive have Harvard University either?

2024-02-05 21:05 UTC, lcerrato commented
@AlisonBabeu I didn't realize there was a Harvard here.  I must have missed that comment sorry.

2024-02-05 21:07 UTC, lcerrato commented
@AlisonBabeu  HUP is artifact of the original files so it was originally there but I did not cross check with the print when I created cts files.

2024-02-05 21:16 UTC, lcerrato commented
@AlisonBabeu Thank you! This is why I wanted reviews.

2024-02-09 18:49 UTC, lcerrato commented
@AlisonBabeu  Is there anything else here?

2024-02-09 20:58 UTC, AlisonBabeu commented
hi @lcerrato the only other thought I had while looking last night although it wasn't important, was that we don't normally include a range of dates do we for publications, but instead put the specific year for each volume. Other than that looks great!

2024-02-09 23:57 UTC, lcerrato commented
@AlisonBabeu  Yes, that was left from the original files. The letters do span two volumes, incidentally. There will be more revisions probably because the batch is not done yet. So there are likely to be further refinements across the whole batch.

2024-02-10 01:10 UTC, merged