(grc_conversion) EpiDoc and CTS conversion
PerseusDL/canonical-greekLit pull request #1608
Opened 2024-03-19 23:32 UTC by lcerrato

#1399 continues with tlg 0086 batch

2024-03-26 15:31 UTC, AlisonBabeu commented on data/tlg0086/tlg010/__cts__.xml
I think that should be Bywater, Ingram!

2024-03-26 16:14 UTC, AlisonBabeu commented on data/tlg0086/tlg029/tlg0086.tlg029.perseus-grc2.xml
So I noticed there are two structured bibls in this file, including this second one:

           `  <biblStruct>` 
              `  <monogr>` 
                 `  <author>Aristotle</author>` 
                  ` <title>Aristotle in 23 Volumes, Vol. 18</title>` 
                 `  <imprint>` 
                     ` <publisher>Harvard University Press, Cambridge, Mass., London</publisher>` 
                  `    <date>1935</date>` 
                 `  </imprint>` 
            `    </monogr>` 
           `  </biblStruct>`

I was wondering if this second couldn't be captured instead in a series statement, or if this was just left by accident.

2024-03-26 16:15 UTC, AlisonBabeu requested changes
hi @lcerrato just one or two changes!

2024-03-27 16:52 UTC, lcerrato commented on data/tlg0086/tlg029/tlg0086.tlg029.perseus-grc2.xml
That was the original that should be deleted.

2024-04-01 21:11 UTC, merged