tlg0059.tlg005_tlg017
PerseusDL/canonical-greekLit pull request #1612
Opened 2024-04-11 17:54 UTC by AlisonBabeu

Second batch of Plato English translation, minor CTS and bibliographic data changes.

2024-04-11 19:42 UTC, lcerrato requested changes
I think we were adding the "printing" disclaimer to the cts files for anything post 1922?

2024-04-11 19:42 UTC, lcerrato commented on data/tlg0059/tlg005/tlg0059.tlg005.perseus-eng2.xml
> +        <ref target="https://hdl.handle.net/2027/uva.x000303015?urlappend=%3Bseq=21%3Bownerid=27021597769027172-25">Internet Archive</ref>
HathiTrust or Internet Archive?

2024-04-12 19:32 UTC, lcerrato approved these changes

2024-04-22 14:55 UTC, AlisonBabeu commented
hi @lcerrato you know I think we were adding (printing) but I believe there are a number of files where that didn't happen.I will make sure to take care of that with the rest of the Plato editions and do a last pass to make sure they are all standard.

2024-04-22 14:55 UTC, merged