(grc_conversion) continued EpiDoc and CTS conversion work
PerseusDL/canonical-greekLit pull request #1631
Opened 2024-06-06 17:33 UTC by lcerrato

work on #1399 
fix #1630

2024-06-10 14:42 UTC, AlisonBabeu commented on data/tlg0027/tlg003/__cts__.xml
> -        <ti:description xml:lang="mul">Andocides. Minor Attic Orators, Vol. 1. Maidment, K. J., editor. London: William Heinemann, Ltd.; Cambridge, MA: Harvard University Press, 1941.</ti:description
You have changed editor to translator here again.

2024-06-10 14:44 UTC, AlisonBabeu commented on data/tlg0027/tlg004/__cts__.xml
> +        <ti:description xml:lang="mul">Andocides. Minor Attic Orators, Vol. 1. Maidment, Kenneth John, translator. London: William Heinemann, Ltd.; Cambridge, MA: Harvard University Press, 1941 (1960
This should be editor not translator.

2024-06-10 14:48 UTC, AlisonBabeu requested changes
hi @lcerrato just one minor change in the cts_xml files!

2024-06-10 15:45 UTC, lcerrato commented
@AlisonBabeu  I think I have them all?

2024-06-11 15:08 UTC, AlisonBabeu approved these changes
hi @lcerrato you definitely have them all!

2024-06-11 18:30 UTC, merged