Plutarch OCR corrections; 079-089
PerseusDL/canonical-greekLit pull request #1635
Opened 2024-06-27 21:11 UTC by helmadik

2024-06-27 21:56 UTC, lcerrato requested changes
There is an error in the testing.

2024-06-27 21:56 UTC, lcerrato commented on data/tlg0007/tlg084a/tlg0007.tlg084a.perseus-grc4.xml
> +<div n="40" subtype="section" type=I g"textpart"><p rend="indent"> <q>διὰ τί τῷ ἱερεῖ τοῦ Διὸς οὐκ ἔξεστιν ἐν <pb xml:id="v.2.p.276" /> ὑπαίθρῳ ἀλείφεσθαι;</q> πότερον ὅτι καὶ παῖδας γυμνοῦσθαι πατρὸ
Stray characters were introduced here:
`<div n="40" subtype="section" type=I g"textpart"><p rend="indent">`

2024-06-27 21:56 UTC, lcerrato commented
There appears to be an error:
tlg0007.tlg084a.perseus-grc4.xml	 
fatal: Open quote is expected for attribute "type" associated with an  element type  "div". [In (L163 C36)]

2024-06-27 22:17 UTC, helmadik commented
oh stupid. Will repair.

2024-06-28 16:58 UTC, helmadik commented
@lcerrato Never sure about git but I think the updated file is now in this queue.

2024-07-01 16:27 UTC, lcerrato approved these changes

2024-07-01 16:27 UTC, merged